### PR TITLE
[Spinnaker] Correct Spinnaker_C preset to bring back enum generation for 'spinError'

### LINKED ISSUE #477: What gradle dependencies are needed
I have some code here: https://github.com/phelgren/Transcode-video-and-audio-using-the-bytedeco-libs  that I am currently running on RHEL5 (manually built and compiled) and on CentOS7 (build using Maven) .  I am trying to get the code to run on Windows 10.  Not much difference between the the Windows 10 and CentOS7 code except one is built with Maven and one uses Gradle.  Both the CentOS7 and the Windows code is built in the same workspace in Eclipse on Windows 10.  Both deploy to Tomcat (8.0) one as a war the other as an OSGI module.  The Windows 10 runtime fails with a NoClassDefFoundError:

Exception in thread "Thread-52" java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.avformat$AVFormatContext
	at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:471)
	at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:465)
	at org.bsfinternational.media.process.MergeUsingFFMPEG.run(MergeUsingFFMPEG.java:266)
	at java.lang.Thread.run(Thread.java:748)

The Gradle dependencies look like this:
 
// https://mvnrepository.com/artifact/org.bytedeco.javacpp - STUFF
	compileInclude group: 'org.bytedeco', name: 'javacpp', version: '1.3.3'	
	compileInclude group: 'org.bytedeco', name: 'javacv-platform', version: '1.3.3'
	compileInclude group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '3.2.1-1.3'
	compileInclude group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.2.0-1.3'
	compileInclude group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg-platform', version: '3.2.1-1.3'

Not a whole lot different from the Maven POM entries:
	<dependency>
	    <groupId>org.bytedeco</groupId>
	    <artifactId>javacpp</artifactId>
	    <version>1.3.3</version>
	    <scope>provided</scope>
	</dependency>
	
	
	<dependency>
	    <groupId>org.bytedeco</groupId>
	    <artifactId>javacv-platform</artifactId>
	    <version>1.3.3</version>
	    <scope>provided</scope>
	</dependency>
	
	
	<dependency>
	    <groupId>org.bytedeco.javacpp-presets</groupId>
	    <artifactId>opencv</artifactId>
	    <version>3.2.0-1.3</version>
	    <scope>provided</scope>
	</dependency>
	
	
	<dependency>
	    <groupId>org.bytedeco</groupId>
	    <artifactId>javacpp-presets</artifactId>
	    <version>1.3</version>
	    <type>pom</type>
	</dependency>

	
	<dependency>
	    <groupId>org.bytedeco.javacpp-presets</groupId>
	    <artifactId>ffmpeg</artifactId>
	    <version>3.2.1-1.3</version>
	    <scope>provided</scope>
	</dependency>
	
     <dependency>
           <groupId>org.bytedeco.javacpp-presets</groupId>
           <artifactId>ffmpeg</artifactId>
           	<version>3.2.1-1.3</version>
           <classifier>windows-x86_64</classifier>
           <scope>provided</scope>
       </dependency>

So, I don't see a whole lot different but I wonder is there is something I need to change to accommodate Windows vs Linux?  I don't quite see what is missing that is causing the failure.  Something simple (I hope)

### PR DESCRIPTION
**Pull request by jpsacha**
After JavaCPP fix #477, `enum` for `spinError` was no longer generated. Add line in `Spinaker_C` preset to force `enum` generation and make sure that it is correctly named in generated Java code.

Large part of the diff is due to `enum`s in generated code no longer having prefix "_"

### CODE REVIEW

File: spinnaker/src/main/java/org/bytedeco/spinnaker/presets/Spinnaker_C.java [hunk 1]
```diff
@@ -93,6 +93,9 @@ public void map(InfoMap infoMap) {
                 .put(new Info("SPINC_CALLTYPE").cppTypes().annotations().cppText(""))
                 .put(new Info("SPINC_NO_DECLSPEC_STATEMENTS", "EXTERN_C").define())
                 .put(new Info("SPINNAKERC_API").cppTypes("_spinError").cppText("enum _spinError").define())
+                // spinEnum is not getting generated so force it using enum name "_spinError"
+                //    and give correct generated name "spinError"
+                .put(new Info("_spinError").enumerate().valueTypes("spinError"))
```
Comment (saudet) [inline spinnaker/src/main/java/org/bytedeco/spinnaker/presets/Spinnaker_C.java:98]: That's probably because of the line above. Try to remove that line, and move "SPINNAKERC_API" to the right of "SPINC_CALLTYPE" instead.

Comment (jpsacha) [reply spinnaker/src/main/java/org/bytedeco/spinnaker/presets/Spinnaker_C.java:98]: No sure what you mean to do with "SPINNAKERC_API"?

The line in preset
```
new Info("SPINNAKERC_API").cppTypes("_spinError").cppText("enum _spinError").define()
```
is due to line in C code:
```C
#define SPINNAKERC_API SPINC_IMPORT_EXPORT spinError SPINC_CALLTYPE
```
the usge in C code is:
```C
SPINNAKERC_API spinErrorGetLast(spinError* pError);
```
That is `SPINNAKERC_API` is uised as return value

Comment (saudet) [reply spinnaker/src/main/java/org/bytedeco/spinnaker/presets/Spinnaker_C.java:98]: That's fine, it's going to expand it to "spinError", as long as you make sure it doesn't try to add types to all other macros as well (SPINC_IMPORT_EXPORT, SPINC_CALLTYPE, and whatever else there is).

Comment (jpsacha) [reply spinnaker/src/main/java/org/bytedeco/spinnaker/presets/Spinnaker_C.java:98]: I am not clear if you want me to change something? Is this PR OK?
I can use this Spinnaker preset in a demo code that interacts with a camera, so in that sense it is fine.

Comment (saudet) [reply spinnaker/src/main/java/org/bytedeco/spinnaker/presets/Spinnaker_C.java:98]: Please try to replace these 3 lines:
```java
.put(new Info("SPINC_CALLTYPE").cppTypes().annotations().cppText(""))
.put(new Info("SPINNAKERC_API").cppTypes("_spinError").cppText("enum _spinError").define())
.put(new Info("_spinError").enumerate().valueTypes("spinError"))
```
with this single line:
```java
.put(new Info("SPINC_CALLTYPE", "SPINNAKERC_API", "SPINC_IMPORT_EXPORT").cppTypes().annotations().cppText(""))
```

Comment (jpsacha) [reply spinnaker/src/main/java/org/bytedeco/spinnaker/presets/Spinnaker_C.java:98]: OK. I have to run. I will try tomorrow

**Comment by jpsacha** [comment]
I used the suggestion and updated PR.

By the way, I noticed that some wrappers have different return values, some have `spinError `, some `@Cast("spinError") int`. For instance, in lines 6033-6035 of `global/Spinnaker_C.java`. Notice second method has return `int`. This is similar to previous code on `master` [l.6033](https://github.com/bytedeco/javacpp-presets/blob/edb311b631a1a98bec14aba4e98ad5e390b63a8d/spinnaker/src/gen/java/org/bytedeco/spinnaker/global/Spinnaker_C.java#L6033):
```java
    public static native spinError spinNodeIsImplemented(spinNodeHandle hNode, @Cast("bool8_t*") BytePointer pbResult);
    public static native @Cast("spinError") int spinNodeIsImplemented(spinNodeHandle hNode, @Cast("bool8_t*") ByteBuffer pbResult);
    public static native spinError spinNodeIsImplemented(spinNodeHandle hNode, @Cast("bool8_t*") byte[] pbResult);
```
I do not know what to make up of this. 
Is the generation of that `int` return a bug or an intentional behavior (signature variants) of JavaCPP?
